import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const licenses = await Promise.all([
  readFile(new URL('node_modules/qrcode/license', import.meta.url), 'utf8'),
  readFile(new URL('node_modules/dijkstrajs/LICENSE.md', import.meta.url), 'utf8'),
]);
const result = await build({
  absWorkingDir: fileURLToPath(new URL('.', import.meta.url)),
  entryPoints: ['node_modules/qrcode/lib/browser.js'],
  bundle: true,
  minify: true,
  platform: 'browser',
  format: 'iife',
  globalName: 'QRCode',
  target: 'es2017',
  legalComments: 'inline',
  banner: { js: '/*! qrcode 1.5.4 and dijkstrajs 1.0.3. Generated by scripts/dashboard/vendor.mjs.\n' +
    licenses.join('\n').replaceAll('```', '').trim() + '\n*/' },
  write: false,
});
const asset = new URL('../../src/assets/qrcode.min.js', import.meta.url);
if (process.argv.includes('--check')) {
  assert.equal(await readFile(asset, 'utf8'), result.outputFiles[0].text);
  console.log('Vendored QR bundle matches the locked sources and licenses.');
} else {
  await writeFile(asset, result.outputFiles[0].contents);
  console.log(`Generated ${result.outputFiles[0].contents.length} byte QR bundle.`);
}
